title: [Idle Game to Test True Spending Awareness in Abstracted Versus Non-Abstracted Microtransactions]
description: [Created by Theodore Farland and Benjamin Deschene]
remote_theme: pages-themes/cayman@v0.2.0